name: Deploy Backend Server

on:
  push:
    branches: ["be"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fe
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USER_NAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: |
            cd SmartRent
            git pull
            cd be
            chmod 777 ./checkFileChange.sh
            docker compose down
            docker compose up
